baseURL: 'https://luminocean.github.io/'
languageCode: en-us
title: 昆乱不挡
theme: hugo-theme-zozo
menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      url: /
    - name: Archive
      weight: 20
      identifier: archive
      url: /posts/
    - name: Tags
      weight: 30
      identifier: tags
      url: /tags/
    - name: About
      weight: 40
      identifier: about
      url: /about/
social:
  github: 'https://github.com/luminocean'
publishDir: docs
pygmentsstyle: "trac"
